image: node:18

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli

install:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - ng build --configuration=production --output-path=dist/
    - ls -la dist/
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - cp dist/noe-dev/browser/index.html dist/noe-dev/browser/404.html
  artifacts:
    paths:
      - dist/noe-dev/browser/
  only:
    - master
