image: node:18

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli

install:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - ng build --configuration=production
    - ls -la dist/noe-dev/browser/
  artifacts:
    paths:
      - dist/noe-dev/browser/

deploy:
  stage: deploy
  script:
    - cp dist/noe-dev/browser/index.html dist/noe-dev/browser/404.html
  artifacts:
    paths:
      - dist/noe-dev/browser/
  only:
    - master

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r dist/noe-dev/browser/* public/
  artifacts:
    paths:
      - public
  only:
    - master
