image: node:18

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli

install:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - ng build --configuration=production --output-path=public
  artifacts:
    paths:
      - public/

deploy:
  stage: deploy
  artifacts:
    paths:
      - public/
  only:
    - master
